export const KEYS = {
  USER: {
    GET: "GET_USER",
  },
  HERO_SECTION: {
    GET: "GET_HERO_SECTION",
  },
  WORK_COUNT: {
    GET: "GET_WORK_COUNT",
  },
  OUR_SERVICE: {
    GET: "GET_OUR_SERVICE",
    GET_DETAILS: "GET_SERVICE_DETAILS",
  },
  PORTFOLIO: {
    GET: "GET_PORTFOLIO",
    GET_DETAILS: "GET_PORTFOLIO_DETAILS",
  },
  WORK_EXPERIENCE: {
    GET: "GET_WORK_EXPERIENCE",
  },
  SKILL: {
    GET: "GET_SKILL",
  },
  AWARDS: {
    GET: "GET_AWARDS",
  },
  TESTIMONIAL_DESCRIPTION: {
    GET: "GET_TESTIMONIAL_DESCRIPTION",
  },
  TESTIMONIAL: {
    GET: "GET_TESTIMONIAL",
  },
  BLOG: {
    GET: "GET_BLOG",
    GET_DETAILS: "GET_BLOG_DETAILS",
  },
  CONTACT: {
    POST: "POST_CONTACT",
  },
  SETTING: {
    GET: "GET_SETTING",
  },
  TERMS_CONDITIONS: {
    GET: "GET_TERMS_CONDITIONS",
  },
  PRIVACY_POLICY: {
    GET: "GET_PRIVACY_POLICY",
  },
  SERVICE: {
    GET: "GET_SERVICE",
  },
  BUSINESS_CATEGORY: {
    GET: "GET_BUSINESS_CATEGORY",
  },
  WEBINAR: {
    GET: "GET_WEBINAR",
    REGISTER: "POST_WEBINAR_REGISTER",
    CREATE_ORDER: "POST_WEBINAR_CREATE_ORDER",
    VERIFY_PAYMENT: "POST_WEBINAR_VERIFY_PAYMENT",
    PAYMENT_FAILED: "POST_WEBINAR_PAYMENT_FAILED",
  },
  CLIENT_LOGO: {
    GET: "GET_CLIENT_LOGO",
  },
  PODCAST_SHOW: {
    GET: "GET_PODCAST_SHOW",
  },
  BRAND: {
    GET: "GET_BRAND",
  },
};
