export const ROUTES = {
  HOME: "/",
  ABOUT : "/about",
  CONTACT : "/contact",
  PROJECT : "/project",
  SERVICE : "/service",
  SERVICE_DETAIL : "/service-detail/:id",
  BLOG : "/blog",
  BLOG_DETAIL : "/blog-detail/:id",
  NOT_FOUND : "/404",
  PORTFOLIO : "/portfolio",
  PORTFOLIO_DETAIL : "/portfolio-detail/:id",
  TERMS_CONDITION : "/terms-condition",
  PRIVACY_POLICY : "/privacy-policy",
  BOOK_A_DEMO: "/book-a-demo",
  WEBINAR: "/webinar",
  PAYMENT_SUCCESS: "/book-a-demo/success",
  PAYMENT_FAILED: "/book-a-demo/failed",
};